### ISSUE TITLE
NameError: name 'verify' is not defined

### ISSUE THREAD

**Issue by eragonshadeslayer2030** [Joensw/Reddit-Shorts-Bot#1]
Finished all the steps but when I run it that happens, any ideas?
Ah I just noticed that it isn't finished and that's why. Sorry for bothering.

**Comment by Joensw** [comment]
Hey, thanks for letting me know. I accidentally pushed a version where I had deleted the verify function, that's why it was giving you that error, very silly mistake on my part. It should work in with the latest commit.
