### ISSUE TITLE
Incompatible with RedditVideoMakerBot's times_to_run feature.

### ISSUE THREAD

**Issue by eragonshadeslayer2030** [Joensw/Reddit-Shorts-Bot#2]
When you use the bot and you have in the RedditVideoMakerBot settings a certain times_to_run it will run that many times but this will only upload one of those times. I think that the easiest fix would be to copy the feature from RedditVideoMakerBot and make it so that the whole script runs however many times you want. This would still leave a bug if someone also had a specific number of times_to_run more than 1 in RedditVideoMakerBot but hey, at least you could run it multiple times. I've tried to do this myself but I don't know Python  so I haven't been successful. If it helps, here are where I've found code that involves the times_to_run feature in the RedditVideoMakerBot:

https://github.com/elebumm/RedditVideoMakerBot/blob/master/utils/.config.template.toml
https://github.com/elebumm/RedditVideoMakerBot/blob/master/main.py

**Comment by Joensw** [comment]
Thank you for pointing this out. I will look into it. In the meanwhile I will adjust the README to avoid confusion.

**Comment by Joensw** [comment]
This should work now. Please note a package was added to the requirements that is now also needed.
