### ISSUE TITLE
'dict' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by axen1** [Joensw/Reddit-Shorts-Bot#5]
![image](https://user-images.githubusercontent.com/31828262/195334234-382049d7-bede-4bd9-af5a-944c1c636602.png)

**Comment by axen1** [comment]
![image](https://user-images.githubusercontent.com/31828262/195334451-0efc9e0c-5161-4ae6-a4bd-f730d1ad2815.png)
![image](https://user-images.githubusercontent.com/31828262/195334504-019c7c42-666a-4bc1-8324-a2f1b56333dd.png)

**Comment by Joensw** [comment]
It looks like your config.toml file may not be completely configured, does the Reddit Video Maker Bot work when you use it normally? And does it come up with blue text asking you for input when you run it?

**Comment by axen1** [comment]
Can you send me the config.toml file so I can have a look at it as an example?
email :bahadirkenan@gmail.com

**Comment by Joensw** [comment]
Yep, I sent you an email.
