### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\nakadashimiyako\\Documents\\RedditVideoMakerBot\\config.toml'

### ISSUE THREAD

**Issue by LatteMill** [Joensw/Reddit-Shorts-Bot#7]
Traceback (most recent call last):
  File "C:\Users\nakadashimiyako\Documents\Reddit-Shorts-Bot\main.py", line 95, in <module>
    main()
  File "C:\Users\nakadashimiyako\Documents\Reddit-Shorts-Bot\main.py", line 76, in main
    times_to_run = get_run_times()
  File "C:\Users\nakadashimiyako\Documents\Reddit-Shorts-Bot\main.py", line 21, in get_run_times
    with open(config_path, mode="rb") as fp:
OSError: [Errno 22] Invalid argument: 'C:\\Users\nakadashimiyako\\Documents\\RedditVideoMakerBot\\config.toml'

**Comment by Joensw** [comment]
Apologies that I didn't respond earlier, I was busy with university.

Are you still having this issue?

**Comment by Hvdri** [comment]
I remember having solved the issue. But dont remember how, i dont use it
anymore. Im also busy with university :)

**Comment by LatteMill** [comment]
> Owner

Yes, it still report this error

**Comment by Joensw** [comment]
I've tried to recreate the issue and I could not. 
Would you mind telling me which python version you are using and also sharing your .env file?

**Comment by LatteMill** [comment]
> I've tried to recreate the issue and I could not. Would you mind telling me which python version you are using and also sharing your .env file?

Sorry for a late reply, it's 3.10.x version

**Comment by Joensw** [comment]
There is no config.toml file in this repo. In the required RedditVideoMakerBot repository there is also no config.toml file, until it is created when the program is run for this first time. Running the RedditVideoMakerBot on its own before using this program is important, so the file is created and the bot is configured correctly.

**Comment by Percy1082** [comment]
> There is no config.toml file in this repo. In the required RedditVideoMakerBot repository there is also no config.toml file, until it is created when the program is run for this first time. Running the RedditVideoMakerBot on its own before using this program is important, so the file is created and the bot is configured correctly.

Traceback (most recent call last):
  File "C:\Users\admin018\Documents\Reddit-Shorts-Bot\main.py", line 95, in <module>
    main()
  File "C:\Users\admin018\Documents\Reddit-Shorts-Bot\main.py", line 76, in main
    times_to_run = get_run_times()
  File "C:\Users\admin018\Documents\Reddit-Shorts-Bot\main.py", line 21, in get_run_times
    with open(config_path, mode="rb") as fp:
OSError: [Errno 22] Invalid argument: 'C:\\Users\x07dmin018\\Documents\\RedditVideoMakerBot\\config.toml'

**Comment by Percy1082** [comment]
How could i setting automatically post on Youtube daily ?

**Comment by Joensw** [comment]
> How could i setting automatically post on Youtube daily ?

You can use something like [Windows Task Scheduler](https://www.youtube.com/watch?v=4n2fC97MNac) to automatically run the program daily

**Comment by LatteMill** [comment]
> > How could i setting automatically post on Youtube daily ?
> 
> You can use something like [Windows Task Scheduler](https://www.youtube.com/watch?v=4n2fC97MNac) to automatically run the program daily

Thank you sir
